repos:
  # C++ formatting
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: ['-style=file']

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(docs/|.*\.md)$'
      - id: end-of-file-fixer
        exclude: '^(docs/|.*\.png|.*\.jpg)$'
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=10240']  # 10MB limit
      - id: check-yaml
      - id: check-json
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: fix-byte-order-marker

  # CMake formatting
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: [--in-place]
      - id: cmake-lint

  # Shell script checking
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        args: ['-x']

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '^(test_|.*\.lock|.*\.log)$'

  # Documentation checks
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        exclude: '^(archive/|build/|docs/)'

# Configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
