site_name: Computer Vision Stereo Processing
site_description: Advanced Computer Vision Library for Stereo Image Processing and 3D Reconstruction
site_author: Computer Vision Team
site_url: https://computer-vision-docs.example.com

repo_name: computer-vision
repo_url: https://github.com/computer-vision-project/computer-vision
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Computer Vision Team

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    logo: material/camera
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Building from Source: getting-started/building.md
    - Docker Setup: getting-started/docker.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Calibration: user-guide/calibration.md
    - Stereo Processing: user-guide/stereo-processing.md
    - Point Clouds: user-guide/point-clouds.md
    - Multi-Camera Systems: user-guide/multi-camera.md
    - Streaming Optimization: user-guide/streaming.md
  - API Reference:
    - Core: api/core.md
    - Camera Management: api/camera.md
    - Stereo Matching: api/stereo.md
    - Calibration: api/calibration.md
    - Point Cloud Processing: api/point-cloud.md
    - AI Components: api/ai.md
    - Streaming: api/streaming.md
    - GUI Components: api/gui.md
  - Tutorials:
    - Basic Stereo Setup: tutorials/basic-stereo.md
    - Camera Calibration: tutorials/calibration.md
    - Real-time Processing: tutorials/real-time.md
    - Multi-Camera Sync: tutorials/multi-camera-sync.md
    - Performance Optimization: tutorials/performance.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Build System: development/build-system.md
    - Testing: development/testing.md
    - Code Style: development/code-style.md
    - Performance Reports: development/performance-reports.md
  - Examples:
    - Code Examples: examples/code-examples.md
    - Sample Applications: examples/applications.md
    - Configuration Files: examples/configurations.md
  - Changelog: changelog.md

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: computer-vision-project
      repo: computer-vision
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/computer-vision-project/computer-vision
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/computer-vision/stereo-processing
  version:
    provider: mike
    default: stable
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
