name: CI - CPU only

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-smoke:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git pkg-config libopencv-dev libpcl-dev qt6-base-dev python3 python3-pip
      - name: Configure
        run: ./build.sh
      - name: Run smoke tests
        run: scripts/smoke.sh
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: smoke-reports
          path: reports/smoke
